export const relationshipOptions = [
  { value: "father", label: "Pai" },
  { value: "mother", label: "Mãe" },
  { value: "stepchild", label: "Enteado(a)" },
  { value: "stepfather", label: "Padrasto" },
  { value: "stepmother", label: "Madrasta" },
  { value: "child", label: "Filho(a)" },
  { value: "sibling", label: "Irmão(ã)" },
  { value: "grandparent", label: "Avô/Avó" },
  { value: "uncle_aunt", label: "Tio(a)" },
  { value: "cousin", label: "Primo(a)" },
  { value: "nephew_niece", label: "Sobrinho(a)" },
  { value: "brother_in_law", label: "Cunhado(a)" },
  { value: "father_in_law", label: "Sogro(a)" },
  { value: "son_in_law", label: "Genro/Nora" },
  { value: "godparent", label: "Padrinho/Madrinha" },
  { value: "friend", label: "Amigo(a)" },
  { value: "coworker", label: "Colega de trabalho" },
  { value: "neighbor", label: "Vizinho(a)" },
  { value: "other", label: "Outro" },
];
